### ISSUE TITLE
Provide TypeScript definitions file for ease of use

### ISSUE THREAD

**Issue by J-Cake** [Reon90/glfwJS#1]
I came across this project through the official glfw website and was hoping to use it, but as no typescript definitions exist, this is a little bit more difficult. I'm wondering if there's gonna be some way to generate this quickly. I happened to notice the `/include/ast/glfw3.xml` file and was wondering if this could be used. Similarly the `.h` file could be used for this, but I'm not sure how this would be done. Otherwise, the library works great and is very on-par with the C++ docs. Thank you for this.

**Comment by Reon90** [comment]
@J-Cake I will provide the ts types as soon as possible. Thank you.

**Comment by J-Cake** [comment]
Ah you're a legend, thanks so much

**Comment by Reon90** [comment]
TypeScript definitions file was added.

**Comment by J-Cake** [comment]
Awesome thanks so much !!!
